<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-G2SQ9GRV" ignored="0" name="Ecommerce App Test1" tests="1" failures="1" timestamp="02 Feb 2019 23:59:34 GMT" time="5.822" errors="0">
  <testcase name="Signin" time="0.116" classname="com.RegressionTests.TC_001">
    <failure type="java.lang.AssertionError" message="expected [http://automationpractice.com/index.php?controller=authentication&amp;amp;back=my-account] but found [http://automationpractice.com/index.php]">
      <![CDATA[java.lang.AssertionError: expected [http://automationpractice.com/index.php?controller=authentication&back=my-account] but found [http://automationpractice.com/index.php]
at com.RegressionTests.TC_001.Signin(TC_001.java:19)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- Signin -->
</testsuite> <!-- Ecommerce App Test1 -->
